### ISSUE TITLE
I wish `from_attribute_value` could take a borrowed AttributeValue, rather than moving it

### ISSUE THREAD

**Issue by dcormier** [zenlist/serde_dynamo#4]
I've got a case where I'm using `from_attribute_value` to deserialize just one attribute of an item I got from DynamoDB. I wish I could just pass a ref to the attribute in the hash  (I have a `&AttributeValue`) I get back from Dynamo rather than having to clone it.

Thoughts?

**Comment by bryanburgers** [comment]
Yep, that was a design decision.

If `from_attribute_value` took a reference, then all of the strings coming out of it would need to be cloned.

By taking ownership of the AttributeValue, any string that comes out of the AttributeValue can be moved out instead of cloned out.

For small structures, this probably doesn't matter either way. And obviously, in the case where you want to deserialize an AttributeValue _and_ keep it around, it's a wash, because either you end up cloning the AttributeValue first, or you end up cloning all of the strings that come out.

I think the more common use case, though, is that DynamoDb returns medium-to-large structures, and once a user of the library gets an Item or an AttributeValue, they will usually want it deserialized and not keep around the original, so preferring an interface that reduces clones seems like the right choice to me.

**Comment by bryanburgers** [comment]
The other potential solution would be to allow `from_attribute_value`/`from_item` (or some variant of them) that could take a ref and could return `&str`s instead of `Strings`. I never really looked into that – despite it being completely valid – because it would probably require duplicating all of the deserialization logic to support it, and it's not something Zenlist needs.

If it's a big need, though, it's certainly something that could be considered.

**Comment by dcormier** [comment]
> Yep, that was a design decision.

OK, understood.

> I think the more common use case, though, is that DynamoDb returns medium-to-large structures, and once a user of the library gets an Item or an AttributeValue, they will usually want it deserialized and not keep around the original, so preferring an interface that reduces clones seems like the right choice to me.

Yeah, that probably is _far_ more common. I would expect what I'm trying to do (just check one attribute from the `HashMap` before deserializing the whole thing) to be more unusual.

> The other potential solution would be to allow `from_attribute_value`/`from_item` (or some variant of them) that could take a ref and could return &strs instead of Strings. I never really looked into that – despite it being completely valid – because it would probably require duplicating all of the deserialization logic to support it, and it's not something Zenlist needs.

I'm actually playing with this right now, even if it's not something that's desired for this crate. Mostly because I'm new to Rust and it felt like a good opportunity to learn. I've almost got it to compile. The last thing I seem to be fighting with is the `impl MapAccess for DeserializerMap`. I just can't quite get the lifetimes right. Though, even once I do I wouldn't be surprised if more errors pop up. Not that I'm asking for you to work on this, but if you do want to look I've pushed what I've got [here](https://github.com/zenlist/serde_dynamo/compare/main...dcormier:dc/ref).
