### ISSUE TITLE
Can the `Error` type allow access to or expose the internal `ErrorImpl` type (essentially the source of the error)?

### ISSUE THREAD

**Issue by jkshtj** [zenlist/serde_dynamo#46]
I want to convert the actual errors into my own error types. I'm wondering if there is either an existing way to get the source of the error in the `Error` type or if we could add one.

**Comment by bryanburgers** [comment]
Ha, OK. You’re the first person to ask!

I hid all of the error details in a private enum to make not breaking semantic versioning significantly easier. I kinda modeled it after [serde_json::Error](https://docs.rs/serde_json/latest/serde_json/struct.Error.html).

And then I kinda decided, meh, I won’t expose *anything* until somebody shows up with an actual use case.

And now here’s somebody with an actual use case!

Do you need the underlying details for every individual error type? Do you need “classes” like serde_json has? Do you need something else? I’m curious what you’re trying to differentiate between when you see a serde_dynamo::Error.

**Comment by jain98** [comment]
>I hid all of the error details in a private enum to make not breaking semantic versioning significantly easier. I kinda modeled it after [serde_json::Error](https://docs.rs/serde_json/latest/serde_json/struct.Error.html).

I see.

I really just want to be able to determine the "source" of the error and transform the serde_dynamo error into my own corresponding error type. I do not want to leak internal details about my implementation using serde_dynamo. 

I think we may be able to do this simply by implementing `source` and `message` methods in the `std::error::Error` trait for `serde_dynamo::Error`?

**Comment by bryanburgers** [comment]
_Useful_ error messages and _accessible internals_ are two separate considerations with two separate tradeoffs.

Both of the current decisions are informed by how `serde_json` works.


## Accessible internals

The primary tradeoff for accessible internals is considering what happens when a user of the library updates to a newer version, and weighing that against the utility of a user of the library being able to get at the exact cause of the error.

Right now, we've gone with hidden internals (much like serde_json's `ErrorImpl` is not public [[source]](https://github.com/serde-rs/json/blob/4b9699612f57512b6734b43238c2382186245b31/src/error.rs#L175-L179)).

The original ask of this issue is whether we can tip that tradeoff the other way, and expose the internals of the error, which would require libraries to deal with a breaking change any time we added new error types, using [#![non_exhaustive]](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute) or some other approach.

The open question for me is how much value is added by opening it up vs how much pain is caused in the ecosystem.


## Useful error messages

To provide the sorts of error messages that people would find useful would require identifying *where* in a nested attribute value the error occurred.

To track that, `serde_dynamo` would need to store the key from a [Map](https://docs.rs/serde_dynamo/4.1.0/serde_dynamo/enum.AttributeValue.html#variant.M) or the index from a [List](https://docs.rs/serde_dynamo/4.1.0/serde_dynamo/enum.AttributeValue.html#variant.L) any time one was encountered, because it doesn't know whether an error will occur deserializing the nested value.

And for maps nested in maps nested in maps, each time we parsed a new key, we would have to clone and reallocate for the entire path up to that point and then add the new key.

All of that work needs to be done whether or not an error occurs, because at the point where we have the path information, we haven't deserialized the nested value yet so we don't know if it will fail.

That's a lot of allocations for the 90% case where deserialization succeeds.

For me, there's no open question here. We've made the choice to prioritize performance over getting useful error messages when a deserialization fails, and to me that's the right decision.
