### ISSUE TITLE
`PutItem` throws `PutItemError`: "One of the required keys was not given a value"

### ISSUE THREAD

**Issue by setoelkahfi** [zenlist/serde_dynamo#70]
Hello, this crate has been really helpful ❤️ 

However, I got an error when trying to update an existing item in my table with the given primary key and secondary key. The primary key is `profileId` and the secondary key is `journeyId`.

The Item:
```
Item: {
    "Ok": M({
        "journeyId": S("mylisttooltipjourney"),
        "isJourneyParticipant": Bool(true),
        "journey": M({
            "inactivityThreshold": Null(true),
            "updatedTimestamp": N("1681466785"),
            "steps": L([
                M({ "nextStepId": S("secondTimeDisplayed"), "status": S("COMPLETED"), "stepId": S("firstTimeDisplayed"), "prevStepId": Null(true), "updatedTimestamp": Null(true) }),
                M({ "prevStepId": S("firstTimeDisplayed"), "stepId": S("secondTimeDisplayed"), "status": S("COMPLETED"), "updatedTimestamp": Null(true), "nextStepId": S("thirdTimeDisplayed") }),
                M({ "prevStepId": S("secondTimeDisplayed"), "updatedTimestamp": Null(true), "status": S("COMPLETED"), "nextStepId": Null(true), "stepId": S("thirdTimeDisplayed") })
            ]),
            "currentStep": M({
                "nextStepId": Null(true),
                "updatedTimestamp": Null(true),
                "prevStepId": S("secondTimeDisplayed"),
                "status": S("COMPLETED"),
                "stepId": S("thirdTimeDisplayed")
            }),
            "journeyName": S("My list tooltip journey"),
            "completed": Bool(true),
            "journeyId": S("mylisttooltipjourney")
        }),
        "profileId": S("profile000"),
        "inactivityThreshold": Null(true),
        "journeyServiceUrl": S("https://api-url/endpoint")
    })
}
```

The error:
`ServiceError(ServiceError { source: PutItemError { kind: Unhandled(Unhandled { source: Error { code: Some("ValidationException"), message: Some("One of the required keys was not given a value") ... // more error information here `

Any pointers?

**Comment by bryanburgers** [comment]
If you look closely at the item, you'll see there's an `"Ok"` at the root of it.

I *think* that what you **want** to serialize is a `Journey`, but what you've **actually** serialized is a `Result<Journey, _>`.

Check out the difference between serializing a `Journey` and a `Result<Journey, _>` here (using serde_json instead of serde_dynamo because the former is available on the playground): https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b1ee4f35aae889f177bcf019a64248de

Because the only thing on the top level of the item is the `"Ok"`, DynamoDb doesn't see a `"journeyId"` at the top level of the item.

**Comment by setoelkahfi** [comment]
Yes, I figured that. It works now. Thanks!
